server:
  port: 9091
spring:
  application:
    name: LoadBalancedMainApp
SpringBootProject:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:8083,localhost:8084
    ServerListRefreshInterval: 2000

